package com.jblose.projectEuler.problems;

/**
 * Problem002 Solve: Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2, the first 10 terms
 * will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in
 * the Fibonacci sequence whose values do not exceed four million, find the sum
 * of the even-valued terms.
 * 
 * @author jblose
 * 
 */
public class Problem002 {
	private double answer = 0;
	private double f1;
	private double f2;
	private double f3;
	private double maximumValue;
	
	public Problem002() {
	}

	public void setUp(double maximumValue){
		this.maximumValue = maximumValue;
	}
	
	public double getAnswer() {
		return this.answer;
	}

	public void solve() {
		f1 = 1;
		f2 = 2;
		answer = 2;
		while(f1 < maximumValue && f2 < maximumValue){
			f3 = f1 + f2;
			f1 = f2;
			f2 = f3;
			if (f3 % 2 == 0 && f3 <= maximumValue){
				answer += f3;
			}
		}
	}
}